# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  app:
    build:
      context: "D:\\Projects\\Expouse"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Expouse.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "expouse:dev"
    ports: []
    volumes:
    - "D:\\Projects\\Expouse\\Expouse:/app:rw"
    - "D:\\Projects\\Expouse:/src:rw"
    - "C:\\Users\\User\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
